# Generated by Django 6.1 on 2026-08-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaign_reward_pledge'),
        ('core', '0004_consentlog'),
    ]

    operations = [
    ]
