# Generated by Django 6.1 on 2026-08-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_0004_campaign_reward_pledge_0004_consentlog'),
        ('core', '0006_seed_homepage_content'),
    ]

    operations = [
    ]
