# Generated by Django 6.1 on 2026-09-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Tambua Afrika Ink', max_length=120)),
                ('label', models.CharField(help_text='e.g. Publishing, Core, Theatre', max_length=50)),
                ('description', models.TextField(help_text='Max 300 characters.', max_length=300)),
                ('accent', models.CharField(choices=[('studios', 'Studios (Black)'), ('ink', 'Tambua Ink (Royal Blue)'), ('stage', 'Tambua Stage (Chocolate Brown)'), ('comics', 'Tambua Comics (Silver Grey)'), ('sales', 'Sales & Marketing (Beige / Gold)')], default='studios', max_length=20)),
                ('icon', models.CharField(choices=[('studios', 'Studio Box'), ('ink', 'Ink Pen'), ('stage', 'Theatre / People'), ('comics', 'Comics Grid'), ('sales', 'Commerce Crosshair')], default='studios', max_length=20)),
                ('link_url', models.CharField(blank=True, help_text="Named URL (e.g. 'ink_home') or full URL (https://…).", max_length=200)),
                ('link_text', models.CharField(default='Learn More', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Department',
                'verbose_name_plural': 'Home Departments',
                'ordering': ['order', 'name'],
            },
        ),
    ]
