# Generated by Django 6.1 on 2026-09-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_opencall_guidelines_opencall_slug_and_more'),
        ('core', '0011_opencall_slug_guidelines'),
    ]

    operations = [
    ]
