# Generated by Django 6.1.1 on 2026-09-20 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0004_manualpayment_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Regular, VIP, VVIP', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text="Optional seat limit for this ticket type alone. Leave blank to let it share the show's overall capacity with no separate cap.", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Unchecked types are hidden from buyers.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers are shown first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='stage.show')),
            ],
            options={
                'ordering': ['order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(blank=True, help_text="Which priced tier (VIP, VVIP, ...) this ticket is for. Blank means the show's flat price.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='stage.tickettype'),
        ),
    ]
