# Generated by Django 6.1 on 2026-09-09 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal label, e.g. 'Opening hours' or 'Submission process'.", max_length=120)),
                ('trigger_phrases', models.TextField(help_text="One phrase or keyword per line. If a visitor's message contains any of these (case-insensitive), this intent can match. Example:\nopening hours\nwhat time are you open\nwhen open")),
                ('response', models.TextField(help_text='The reply shown to the visitor. Plain text or simple HTML (e.g. <br>, <a>).')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority intents are checked first when several match the same message.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot intent',
                'verbose_name_plural': 'Chatbot intents',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reply_sent', models.TextField()),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='chatbot.intent')),
            ],
            options={
                'verbose_name': 'Chat log entry',
                'verbose_name_plural': 'Chat log entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
