# Generated by Django 6.0.1 on 2026-01-29 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('manuscript', 'Book Manuscript'), ('script', 'Play Script'), ('comic', 'Comic/Art'), ('audition', 'Audition Tape')], max_length=20)),
                ('file', models.FileField(upload_to='submissions/')),
                ('status', models.CharField(choices=[('received', 'Received'), ('review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
