# Generated by Django 6.1.1 on 2026-09-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional cover/poster image for this submission.', null=True, upload_to='submissions/posters/'),
        ),
    ]
