import uuid

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Show(models.Model):
    """A live performance / production that tickets can be sold for."""

    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=220)
    description = models.TextField(blank=True)
    venue = models.CharField(max_length=200)
    date = models.DateField()
    time = models.TimeField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    capacity = models.PositiveIntegerField(default=100)
    image = models.ImageField(upload_to='stage/shows/', blank=True, null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['date', 'time']

    def __str__(self):
        return f"{self.title} - {self.date}"

    def get_absolute_url(self):
        return reverse('show_detail', kwargs={'slug': self.slug})

    @property
    def is_past(self):
        return self.date < timezone.localdate()

    @property
    def tickets_reserved(self):
        """Seats currently held: paid tickets plus ones still awaiting payment."""
        agg = self.tickets.filter(
            status__in=[Ticket.STATUS_PENDING, Ticket.STATUS_PAID]
        ).aggregate(total=models.Sum('quantity'))
        return agg['total'] or 0

    @property
    def tickets_remaining(self):
        return max(self.capacity - self.tickets_reserved, 0)

    @property
    def is_sold_out(self):
        return self.tickets_remaining <= 0


class TicketType(models.Model):
    """
    A priced tier of ticket for a Show (e.g. Regular, VIP, VVIP).

    Additive/optional: a Show can have zero ticket types, in which case
    buying a ticket still falls back to the Show's own flat `price`
    exactly as before. As soon as a Show has one or more active
    TicketTypes, the purchase flow lets the buyer choose one and the
    ticket is priced/labelled from that type instead.
    """

    show = models.ForeignKey(Show, on_delete=models.CASCADE, related_name='ticket_types')
    name = models.CharField(max_length=100, help_text="e.g. Regular, VIP, VVIP")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    capacity = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text=(
            "Optional seat limit for this ticket type alone. Leave blank to "
            "let it share the show's overall capacity with no separate cap."
        ),
    )
    is_active = models.BooleanField(default=True, help_text="Unchecked types are hidden from buyers.")
    order = models.PositiveIntegerField(default=0, help_text="Lower numbers are shown first.")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['order', 'price']

    def __str__(self):
        return f"{self.name} - {self.show.title}"

    @property
    def tickets_reserved(self):
        agg = self.tickets.filter(
            status__in=[Ticket.STATUS_PENDING, Ticket.STATUS_PAID]
        ).aggregate(total=models.Sum('quantity'))
        return agg['total'] or 0

    @property
    def tickets_remaining(self):
        """None means "no separate cap" -- only the show's overall capacity applies."""
        if self.capacity is None:
            return None
        return max(self.capacity - self.tickets_reserved, 0)

    @property
    def is_sold_out(self):
        return self.capacity is not None and self.tickets_remaining <= 0


class ManualPayment(models.Model):
    """
    Manual M-Pesa/bank payment submitted by a customer.

    The payment is NOT considered successful when the customer submits a
    transaction code. It remains PENDING until an authorized staff member
    checks the actual M-Pesa/bank records and verifies it.
    """

    STATUS_PENDING = 'pending'
    STATUS_VERIFIED = 'verified'
    STATUS_REJECTED = 'rejected'

    STATUS_CHOICES = [
        (STATUS_PENDING, 'Pending Verification'),
        (STATUS_VERIFIED, 'Verified'),
        (STATUS_REJECTED, 'Rejected'),
    ]

    # M-Pesa Paybill configuration.
    # For a Paybill payment the customer uses BOTH values:
    #   Paybill: 522533
    #   Account number: 8126862
    PAYBILL = '522533'
    PAYBILL_ACCOUNT_NUMBER = '8126862'

    # 1355204607 is kept as a company/bank account reference only.
    # It is NOT used as the M-Pesa Paybill account number unless the
    # business/payment provider explicitly confirms that arrangement.
    COMPANY_ACCOUNT_NUMBER = '1355204607'

    ticket = models.OneToOneField(
        'Ticket',
        on_delete=models.CASCADE,
        related_name='manual_payment',
    )
    payment_reference = models.CharField(
        max_length=30,
        unique=True,
        db_index=True,
        help_text='Reference generated by Tambua Afrika Studios and given to the customer.',
    )
    transaction_code = models.CharField(
        max_length=50,
        unique=True,
        null=True,
        blank=True,
        db_index=True,
        help_text='M-Pesa transaction code submitted by the customer.',
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    paybill = models.CharField(max_length=20, default=PAYBILL)
    account_number = models.CharField(
        max_length=30,
        default=PAYBILL_ACCOUNT_NUMBER,
        help_text='M-Pesa Paybill account number supplied to the customer.',
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default=STATUS_PENDING,
        db_index=True,
    )
    submitted_at = models.DateTimeField(null=True, blank=True)
    verified_at = models.DateTimeField(null=True, blank=True)
    verified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='manual_payments_verified',
    )
    rejection_reason = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.payment_reference} - {self.ticket.ticket_code} ({self.get_status_display()})"

    @staticmethod
    def generate_reference():
        # UUID gives enough entropy while keeping the reference short.
        return f"TAS-{uuid.uuid4().hex[:8].upper()}"



class Ticket(models.Model):
    """
    A ticket reservation for a Show.

    Flow: user reserves seats -> status starts as 'pending_payment' ->
    user pays out-of-band (M-Pesa/bank) -> submits the M-Pesa transaction
    code -> payment stays pending until staff verifies it -> ticket is
    marked 'paid' and becomes a valid ticket.

    Automatic gateway payments can still call `mark_as_paid()` from their
    verified callback/IPN.
    """

    STATUS_PENDING = 'pending_payment'
    STATUS_PAID = 'paid'
    STATUS_CANCELLED = 'cancelled'
    STATUS_CHOICES = [
        (STATUS_PENDING, 'Awaiting Payment'),
        (STATUS_PAID, 'Paid'),
        (STATUS_CANCELLED, 'Cancelled'),
    ]

    show = models.ForeignKey(Show, on_delete=models.CASCADE, related_name='tickets')
    ticket_type = models.ForeignKey(
        TicketType,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='tickets',
        help_text="Which priced tier (VIP, VVIP, ...) this ticket is for. Blank means the show's flat price.",
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='tickets')
    quantity = models.PositiveIntegerField(default=1)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True)
    ticket_code = models.CharField(max_length=20, unique=True, editable=False)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_PENDING)
    payment_reference = models.CharField(
        max_length=100, blank=True,
        help_text="M-Pesa code or bank reference supplied by the buyer."
    )
    pesapal_tracking_id = models.CharField(
        max_length=100, blank=True,
        help_text="Pesapal's OrderTrackingId for this payment, if paid via Pesapal.",
    )
    qr_code = models.ImageField(upload_to='stage/tickets/qrcodes/', blank=True, null=True)
    checked_in = models.BooleanField(default=False)
    checked_in_at = models.DateTimeField(null=True, blank=True)
    checked_in_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name='tickets_checked_in',
        help_text="Which staff member scanned/checked this ticket in at the door.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    paid_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.ticket_code} - {self.show.title} ({self.get_status_display()})"

    def save(self, *args, **kwargs):
        if not self.ticket_code:
            self.ticket_code = self._generate_code()
        if not self.total_amount:
            self.total_amount = self.unit_price * self.quantity
        super().save(*args, **kwargs)

    @staticmethod
    def _generate_code():
        return f"TAS-{uuid.uuid4().hex[:10].upper()}"

    def mark_as_paid(self, reference=''):
        """
        Called by both the manual reference form AND the Pesapal
        callback/IPN handlers -- whichever confirms payment first wins.
        Generates the check-in QR code and emails it on the transition
        into 'paid' (not on every call, so a duplicate IPN retry doesn't
        re-send the email or regenerate the QR).
        """
        already_paid = self.status == self.STATUS_PAID
        self.status = self.STATUS_PAID
        self.paid_at = self.paid_at or timezone.now()
        if reference:
            self.payment_reference = reference
        if not self.qr_code:
            self._generate_qr_code()
        self.save()
        if not already_paid:
            self._send_ticket_confirmation_email()

    def _verify_url(self):
        path = reverse('admin_ticket_verify_code', kwargs={'ticket_code': self.ticket_code})
        return f"{settings.SITE_BASE_URL}{path}"

    def _generate_qr_code(self):
        """
        Encodes the door-verification URL (not just the bare ticket
        code) so scanning it with any phone camera opens straight to
        the admin check-in page. That page itself requires a staff
        login, so the QR image alone isn't enough to fake a check-in --
        it just saves an admin from typing the code by hand.
        """
        import qrcode
        from io import BytesIO
        from django.core.files.base import ContentFile

        img = qrcode.make(self._verify_url())
        buffer = BytesIO()
        img.save(buffer, format='PNG')
        self.qr_code.save(f"{self.ticket_code}.png", ContentFile(buffer.getvalue()), save=False)

    def _send_ticket_confirmation_email(self):
        from django.core.mail import EmailMultiAlternatives
        from django.template.loader import render_to_string
        from email.mime.image import MIMEImage

        context = {'ticket': self, 'verify_url': self._verify_url()}
        text_body = render_to_string('emails/ticket_confirmation.txt', context)
        html_body = render_to_string('emails/ticket_confirmation.html', context)

        email = EmailMultiAlternatives(
            subject=f"Your ticket for {self.show.title} — {self.ticket_code}",
            body=text_body,
            from_email=settings.DEFAULT_FROM_EMAIL,
            to=[self.user.email],
        )
        email.attach_alternative(html_body, 'text/html')
       
        if self.qr_code:
            self.qr_code.open('rb')
            qr_bytes = self.qr_code.read()
            self.qr_code.close()

            # Inline (renders inside the email body via cid:qr_code)
            inline_image = MIMEImage(qr_bytes)
            inline_image.add_header('Content-ID', '<qr_code>')
            inline_image.add_header('Content-Disposition', 'inline', filename=f"{self.ticket_code}-qr.png")
            email.attach(inline_image)

            # Also a plain attachment, so it's unambiguously downloadable
            # as its own file even in clients that don't render inline images.
            email.attach(f"{self.ticket_code}-qr.png", qr_bytes, 'image/png')

        email.send(fail_silently=True)

    @property
    def is_paid(self):
        return self.status == self.STATUS_PAID
